# -*- coding: utf-8 -*-
"""DOcgenie.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZX6X7YJtdBa3C-bQDG3djg0wk8PADbmi
"""

!pip install -U transformers

#use a pipeline as a high-level -helper
from transformers import pipeline
pipe = pipeline("text-generation",model="ibm-granite/granite-3.3-2b-instruct")
message = [
     {"role":"user","content":"who are you?"},
]
pipe(message)

# Load model directly
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained(
    "ibm-granite/granite-3.3-2b-instruct"
)

model = AutoModelForCausalLM.from_pretrained(
    "ibm-granite/granite-3.3-2b-instruct"
)

messages = [
    {"role": "user", "content": "Who are you?"},
]

inputs = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt=True,
    tokenize=True,
    return_dict=True,
    return_tensors="pt",
).to(model.device)

outputs = model.generate(**inputs, max_new_tokens=40)

print(
    tokenizer.decode(
        outputs[0][inputs["input_ids"].shape[-1]:]
    )
)

!pip install -q gradio transformers torch black autopep8

# Install required packages (run this once)
!pip install -q gradio transformers torch black autopep8 reportlab requests

# Imports
import gradio as gr
import ast
from datetime import datetime
from pathlib import Path
import urllib.parse
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer

# --- Analyzer Class ---
class DocGenieAnalyzer:
    """Analyze Python functions and generate professional docstrings"""

    @staticmethod
    def extract_function_signature(code):
        """Extract function name, parameters, return type from code"""
        try:
            tree = ast.parse(code)
            func_def = tree.body[0]
            if not isinstance(func_def, ast.FunctionDef):
                return None
            func_name = func_def.name
            params = []
            for arg in func_def.args.args:
                param_type = "Any"
                if arg.annotation:
                    param_type = ast.unparse(arg.annotation) if hasattr(ast, "unparse") else "Any"
                params.append({"name": arg.arg, "type": param_type, "default": None})
            return {"name": func_name, "params": params, "return_type": "Any"}
        except Exception as e:
            print("Error parsing function:", e)
            return None

    @staticmethod
    def analyze_function_logic(code):
        """Analyze function body logic"""
        analysis = {
            "has_loops": False,
            "has_conditions": False,
            "has_return": False,
            "loop_types": [],
            "condition_types": [],
            "operations": [],
            "return_types": [],
            "variables_used": set(),
            "function_calls": [],
            "description": "",
        }
        try:
            tree = ast.parse(code)
            if not tree.body or not isinstance(tree.body[0], ast.FunctionDef):
                return analysis
            func_def = tree.body[0]
            for node in ast.walk(func_def):
                if isinstance(node, (ast.For, ast.While)):
                    analysis["has_loops"] = True
                    analysis["loop_types"].append("for" if isinstance(node, ast.For) else "while")
                if isinstance(node, (ast.If, ast.IfExp)):
                    analysis["has_conditions"] = True
                    analysis["condition_types"].append("if")
                if isinstance(node, ast.Return):
                    analysis["has_return"] = True
                if isinstance(node, ast.Name) and isinstance(node.ctx, ast.Load):
                    analysis["variables_used"].add(node.id)
                if isinstance(node, ast.Call):
                    if isinstance(node.func, ast.Name):
                        analysis["function_calls"].append(node.func.id)
                    elif isinstance(node.func, ast.Attribute):
                        analysis["function_calls"].append(node.func.attr)
            # Simple description
            if analysis["has_loops"] and analysis["has_conditions"]:
                analysis["description"] = "Iterates through data and applies conditional logic."
            elif analysis["has_loops"]:
                analysis["description"] = "Processes data using iterative loops."
            elif analysis["has_conditions"]:
                analysis["description"] = "Executes code based on conditions."
            elif analysis["has_return"]:
                analysis["description"] = "Calculates and returns a result."
            else:
                analysis["description"] = "Performs a sequence of operations."
        except Exception as e:
            print("Error analyzing function:", e)
        return analysis

    @staticmethod
    def generate_google_docstring(signature, analysis, code):
        """Generate Google-style docstring"""
        summary = analysis.get("description", "Processes input and returns result.")
        docstring = f'    """{summary}\n'
        if signature and signature["params"]:
            docstring += "\n    Args:\n"
            for param in signature["params"]:
                default_str = f" (default: {param['default']})" if param["default"] else ""
                docstring += f"        {param['name']} ({param['type']}): Parameter for controlling {param['name']} behavior{default_str}.\n"
        docstring += f"\n    Returns:\n        {signature['return_type']}: The result of the computation.\n"
        docstring += '    """\n'
        return docstring

    @staticmethod
    def generate_numpy_docstring(signature, analysis, code):
        """Generate NumPy-style docstring"""
        summary = analysis.get("description", "Processes input and returns result.")
        docstring = f'    """{summary}\n'
        if signature and signature["params"]:
            docstring += "\n    Parameters\n    ----------\n"
            for param in signature["params"]:
                default_str = f", default: {param['default']}" if param["default"] else ""
                docstring += f"    {param['name']} : {param['type']}{default_str}\n"
                docstring += f"        Parameter for controlling {param['name']} behavior.\n"
        docstring += f"\n    Returns\n    -------\n    {signature['return_type']}\n"
        docstring += f"        The result of the computation.\n"
        docstring += '    """\n'
        return docstring


# --- Global Variables ---
analyzer = DocGenieAnalyzer()
generation_history = []


# --- Helper Functions ---
def generate_docstring(code, style):
    global generation_history
    sig = analyzer.extract_function_signature(code)
    if not sig:
        return code, "Error: Could not parse function signature."
    analysis = analyzer.analyze_function_logic(code)
    if style == "google":
        doc = analyzer.generate_google_docstring(sig, analysis, code)
    else:
        doc = analyzer.generate_numpy_docstring(sig, analysis, code)
    # Insert docstring after def line
    lines = code.splitlines()
    for i, line in enumerate(lines):
        if line.strip().startswith("def "):
            indent = len(line) - len(line.lstrip()) + 4
            lines.insert(i + 1, " " * (indent - 4) + doc)
            break
    new_code = "\n".join(lines)
    generation_history.append((code, new_code, style))
    return new_code, "Docstring generated successfully!"


def process_upload(file_obj):
    if file_obj is None:
        return "", "No file uploaded."
    try:
        with open(file_obj.name, "r") as f:
            content = f.read()
        return content, f"File '{Path(file_obj.name).name}' uploaded successfully."
    except Exception as e:
        return "", f"Error reading file: {e}"


def clear_history():
    global generation_history
    generation_history = []
    return "History cleared."


def download_txt():
    global generation_history
    if not generation_history:
        return None, "No generated docstrings."
    txt_content = ""
    for original, generated, style in generation_history:
        txt_content += f"Original Code:\n{original}\n\nGenerated {style.capitalize()} Docstring:\n{generated}\n\n{'-'*50}\n"
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    file_name = f"docstrings_{timestamp}.txt"
    with open(file_name, "w", encoding="utf-8") as f:
        f.write(txt_content)
    return file_name, "TXT file generated."


def generate_whatsapp_link():
    if generation_history:
        latest = generation_history[-1][1]
        msg = f"Check out this Python code with a generated docstring:\n\n```python\n{latest}\n```"
        return f"https://wa.me/?text={urllib.parse.quote(msg)}"
    return "No docstring generated."


def generate_facebook_link():
    if generation_history:
        latest = generation_history[-1][1]
        dummy_url = "https://example.com/generated_code?code=" + urllib.parse.quote(latest)
        return f"https://www.facebook.com/sharer/sharer.php?u={dummy_url}"
    return "No docstring generated."


# --- Gradio Interface ---
with gr.Blocks(title="DocGenie: AI-Powered Docstring Generator") as demo:
    gr.Markdown("## Professional Python Function Docstring Generator")
    gr.Markdown("Transform your Python functions with AI-powered, accurate documentation!")

    with gr.Row():
        with gr.Column(scale=3):
            gr.Markdown("### Input Function Code")
            code_input = gr.Code(
                language="python",
                label="Python Function",
                lines=10,
                value="def calculate_factorial(n):\n    if n == 0:\n        return 1\n    return n * calculate_factorial(n-1)"
            )
            file_upload = gr.File(label="Or Upload .py File", file_types=[".py"])
            upload_status = gr.Textbox(label="Upload Status", interactive=False, lines=1)
            file_upload.change(process_upload, inputs=[file_upload], outputs=[code_input, upload_status])

            docstring_style = gr.Radio(["google", "numpy"], value="google", label="Docstring Style")
            generate_btn = gr.Button("Generate Docstring", size="lg", variant="primary", scale=2)

        with gr.Column(scale=2):
            gr.Markdown("### Generated Output")
            code_output = gr.Code(language="python", label="Function with Docstring", lines=15, interactive=False)
            gen_status = gr.Textbox(label="Status", interactive=False, lines=1)

    generate_btn.click(generate_docstring, inputs=[code_input, docstring_style], outputs=[code_output, gen_status])

    with gr.Column(scale=1):
        gr.Markdown("### Controls")
        clear_btn = gr.Button("Clear History", variant="stop", size="sm")
        clear_btn.click(clear_history, outputs=[upload_status])

        gr.Markdown("---")
        gr.Markdown("### Export")
        txt_btn = gr.Button("Download TXT", size="sm", variant="primary")
        txt_file = gr.File(label="TXT File", interactive=False, visible=True)
        txt_btn.click(download_txt, outputs=[txt_file, gen_status])

        gr.Markdown("---")
        gr.Markdown("### Share")
        whatsapp_btn = gr.Button("WhatsApp", size="sm", variant="secondary")
        facebook_btn = gr.Button("Facebook", size="sm", variant="secondary")
        share_output = gr.Textbox(label="Share Link", interactive=False, lines=4)
        whatsapp_btn.click(generate_whatsapp_link, outputs=[share_output])
        facebook_btn.click(generate_facebook_link, outputs=[share_output])

# Launch
demo.launch()